### ISSUE TITLE
how to ignore files and folders

### ISSUE THREAD

**Issue by Sandros94** [stefanobartoletti/eslint-config#61]
I'm enjoying this eslint config more and more lately, but I'm also noticing that I need to understand flat configs a bit more.

One particular aspect I'm not fully understanding is how to ignore files:

reading the official [eslint docs](https://eslint.org/docs/latest/use/configure/configuration-files-new#excluding-files-with-ignores) I do see that I should write something like this to ignore two specific folder and files:
```js
// eslint.config.js
import { nuxt, stefanobartoletti, tailwind } from '@stefanobartoletti/eslint-config'

export default stefanobartoletti(
  {},
  nuxt,
  tailwind,
  {
    rules: {
      // my rules
    },
    ignores: [
      'folder/subFolder/**', // This does NOT ignore all subsubfolders and files
      'otherFolder/*.html', // This does NOT ignore `.html` files in that folder
    ],
  },
)
```

but since it doesn't work I tried to pass them to antfu's config and for some reason it works:
```js
// eslint.config.js
import { nuxt, stefanobartoletti, tailwind } from '@stefanobartoletti/eslint-config'

export default stefanobartoletti(
  {
    ignores: [
      'folder/subFolder/**', // This will ignore all subsubfolders and files
      'otherFolder/*.html', // This will ignore only `.html` files in that folder
    ],
  },
  nuxt,
  tailwind,
  {
    rules: {
      // my rules
    },
  },
)
```

So at this point I'm not sure if this is me not understanding or there is a bug

**Comment by stefanobartoletti** [comment]
Yes, you should insert global ignores in the first object, along with other options, as per antfu's readme https://github.com/antfu/eslint-config?tab=readme-ov-file#customization

So your second try is the correct one.

I'm not sure about adding ignores in subsequent config objects, theoretically they would affect only that rule, but to be honest I never needed this fine-grain so I cannot tell you a lot more.

This is an example of how I added ignore into one of my projects:

```js
import { nuxt, stefanobartoletti, tailwind } from '@stefanobartoletti/eslint-config'

export default stefanobartoletti(
  {
    ignores: [
      '**/public/**/*',
    ],
  }, // Options, required
  nuxt,
  tailwind,
  {
    rules: {
      'vue/no-template-shadow': 'off',
    },
  },
)
```

Just for testing, I tried to add an ignore to the `vue/no-template-shadow` and it does not seem to work as expected.



Some notes:

- My own config is basically just some extra rules added on top of antfu's one, and apart from testing it I'm not able to edit its core behavior. I'm not sure if this is a bug or just working as intended, you may want to ask directly in that repository for clarifications. Feel free to link this issue if it helps to give more context.
- Keep in mind that the base of that config is a "factory function" that builds the final config, so the API may be a little different from the default eslint config format.
- You can try to run `npx eslint-flat-config-viewer` to explore the final configuration and see what rules are actually used.

**Comment by Sandros94** [comment]
> [...] you may want to ask directly in that repository for clarifications. [...]

I feel like I need to experiment a bit more first

> - You can try to run `npx eslint-flat-config-viewer` to explore the final configuration and see what rules are actually used.

Forgot that this tool existed, thanks for pointing it out
